@echo off
echo .

rem GeneMi   ,   2013/Jan/26  Saturday  13:32pm
rem AxErd-run-Caller.BAT




set ModuOfficial=Accounts payable
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Accounts receivable
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Budgeting
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Cash and bank management
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Compliance and internal controls
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Financial management
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Fixed assets
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=General ledger
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Human resources
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Inventory and warehouse management
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Procurement and sourcing
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Production control
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Project management and accounting
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Retail
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Sales and marketing
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Service management
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Travel and expense
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .



echo ----- End of Formals, Start of Informals -----------------------
echo .



set ModuOfficial=AIF
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=AppConfig
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Business Intelligence
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Client
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Compiler
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Developer and Partner Tools
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Dynamics Online
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Enterprise Portal
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Global financial management - _W
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Global financial management - Asia Pacific
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Global financial management - Eastern Europe
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Global financial management - Latin America
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Global financial management - North America
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Global financial management - Russia
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Global financial management - Western Europe
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Infrastructure
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Manufacturing
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=No Owner
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Office Business
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Public Sector SL1
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Server and Tools
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Setup
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Tax
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Upgrade framework
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .


set ModuOfficial=Workflow
echo %1  "%ModuOfficial%"
call AxErd-run.bat  %1  "%ModuOfficial%"
echo .



rem ---------------

set ModuFile=
set ModuOfficial=


@echo End of %0
